import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import yaml from "js-yaml";

export const CONFIG_FILENAME = ".privacypolicy.yml";

export type SrcLawyerTier = "free" | "byok" | "managed";

export interface SrcLawyerLlmConfig {
  provider: "anthropic";
  apiKeyEnvVar: string | null;
}

export interface SrcLawyerConfig {
  entityLocation: string | null;
  targetMarkets: string[];
  industry: string | null;
  collectsChildrensData: boolean;
  tier?: SrcLawyerTier;
  llm?: SrcLawyerLlmConfig;
}

export const DEFAULT_CONFIG: SrcLawyerConfig = {
  entityLocation: null,
  targetMarkets: [],
  industry: null,
  collectsChildrensData: false,
  tier: "free",
};

export function configPath(root: string): string {
  return join(root, CONFIG_FILENAME);
}

export function loadConfig(root: string): SrcLawyerConfig | null {
  const path = configPath(root);
  if (!existsSync(path)) return null;
  const raw = readFileSync(path, "utf8");
  return { ...DEFAULT_CONFIG, ...(yaml.load(raw) as Partial<SrcLawyerConfig>) };
}

export function writeConfig(root: string, config: SrcLawyerConfig): void {
  const path = configPath(root);
  const header = "# Generated by srclawyer init. Safe to edit by hand.\n";
  writeFileSync(path, header + yaml.dump(config), "utf8");
}
